export const Types = {
    LOGIN_LOADING: "LOGIN_LOADING",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    PROFILE_DETAILS_LOADING : "PROFILE_DETAILS_LOADING",
    PROFILE_DETAILS_SUCCESS : "PROFILE_DETAILS_SUCCESS",
    PROFILE_DETAILS_FAILURE : "PROFILE_DETAILS_FAILURE",
}